#!/bin/bash
aurdir="$HOME/.aur"

download() {
  echo "note: only folders in $aurdir get updated."
  local packages=$(pacman -Sl)
  local depends
  mkdir -p $aurdir
  cd $aurdir
  for arg in $@; do
    depends=`curl -sg "https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=$arg"`
    if [[ $(echo $depends | jshon -e results) != "[]" ]]; then
      depends=$(echo $depends | jshon -e results -e 0 -e Depends -a -u)
      git clone https://aur.archlinux.org/$arg.git 2> /dev/null
      echo ":: $arg downloaded $aurdir/$arg"
      for dep in $depends; do
        echo $packages | grep $dep > /dev/null
        if [[ $(echo $?) == 1 ]]; then
          git clone https://aur.archlinux.org/$dep.git 2> /dev/null
          echo ":: $dep downloaded to $aurdir/$dep"
        fi
      done
    fi
  done
}

update() {
  mkdir -p $aurdir
  cd $aurdir
  for dir in $(ls); do
    cd $dir
    if [[ $(git pull) != "Already up-to-date." ]]; then
      echo ":: $dir needs to be updated in $aurdir/$dir"
    fi
    cd ..
  done
}

search() {
  curl -s "https://aur.archlinux.org/rpc/?v=5&type=search&arg=$@" \
           | jshon -e results -a -e Name -u
}

if [[ $1 == "-d" ]]; then
  download $(echo $@ | cut -d' ' -f2-)
elif [[ $1 == "-u" ]]; then
  update
elif [[ $1 == "-s" ]]; then
  search $(echo $@ | cut -d' ' -f2-)
else
  echo "yam aur helper: -d = download, -u = update, -s = search"
fi
